### PR TITLE
Read airports with missing frequency and set them to 0.0

### PR DESCRIPTION
**Pull request by nferruzzi**
Hi,

I'm not sure if you are interested, but this PR is to import cup files from openaip.net where airports frequency is almost never set. 

Before it would trigger an exception and ignore the airport, but looking at all my cup files I realized that most airports were missing it and I still need those airports in.

Not sure if forcing it to 0.0 is fine, maybe a null column would work better but I leave it to your review.

There is also a small fix: the exception raised by Reader is ParserError not AttributeError

thanks in advance

### CODE REVIEW

**Comment by Meisterschueler** [comment]
Hi, thank you for the PR. If I understand you correctly the Reader from aerofiles crashes while parsing your CUP file from openaip.net? Then either the Reader or the CUP file is buggy and your PR is a workaround. The better way would be to fix the reader or the CUP file generation. Or you build a separate bugfix script where you alter the CUP files.
I have also some notes to the code:
1. for me a None seems to be better than a 'wrong' value (and 0Mhz is a 'wrong' value...). None is also the default value for the frequency
2. avoid the usage of prints. I would prefer the usage of the python logging

Best regards - Konstantin

**Comment by nferruzzi** [comment]
> Hi, thank you for the PR. If I understand you correctly the Reader from aerofiles crashes while parsing your CUP file from openaip.net? Then either the Reader or the CUP file is buggy and your PR is a workaround. The better way would be to fix the reader or the CUP file generation. Or you build a separate bugfix script where you alter the CUP files.

Yes my first idea was to ask the Reader dev to fix it, but then reading their doc I realized they would not do it because for the library the frequency must be a valid value like 1xx.xx or is not valid at all. 

As you say fixing the cup files before using them would be another way, but I thought that other users of this server would fall for the same problem. I don't know where you get your cups from but to have something convering the whole world I had to use openaip . Maybe with a better source I would probably not care about this problem.

> I have also some notes to the code:
> 
> 1. for me a None seems to be better than a 'wrong' value (and 0Mhz is a 'wrong' value...). None is also the default value for the frequency

ok ! this is better for me too

> 2. avoid the usage of prints. I would prefer the usage of the python logging
> 

ok, I may remove them at all if we are fine with the None value

> Best regards - Konstantin

thank you very much

**Comment by Meisterschueler** [comment]
I cannot reproduce the problem with a missing frequency in the CUP file. I parsed a string without frequency and I got None, just as expected: [see here](https://pastebin.com/WWhEqxm8)
Could you please recheck or provide the CUP file?

**Comment by Meisterschueler** [comment]
No answer from PF

**Pull request closed without merging**
